FROM --platform=linux/amd64 node:20 AS builder

WORKDIR /usr/src/app

ENV NODE_ENV development

COPY ./code/package*.json ./

COPY ./code ./

RUN if [ "$NODE_ENV" = "production" ]; then \
    npm install --omit=dev; \
    else \
    npm install; \
    fi

RUN npm run scss

FROM --platform=linux/amd64 nginx:alpine

COPY --from=builder /usr/src/app/public /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
